### ISSUE TITLE
Error at creation class

### ISSUE THREAD

**Issue by JasterTDC** [kslr/transmission-php#2]
Hello there ! I appreciate your job, but I have a little when I'm trying to create a Transmission object. 

My code is very simple, I'm trying to connect to my transmission server.

```php
$transmission = new Transmission(
    'personal-host',
    9091
);

$transmission->all();
```

```php
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Buzz\Client\AbstractClient::__construct(), 0 passed in /vendor/kslr/transmission-php/lib/Transmission/Client.php on line 76 and at least 1 expected in /vendor/kriswallsmith/buzz/lib/Client/AbstractClient.php:33
```

**Comment by kslr** [comment]
I have fixed this problem because of outdated dependencies, You need to reinstall.

I don't recommend it because it is very old.
